export const INIT_TOPICS = 'INIT_TOPICS'
export const INIT_TOPIC = 'INIT_TOPIC'
export const INIT_BRANDS = 'INIT_BRANDS'
export const INIT_REPORTED_TOPICS = 'INIT_REPORTED_TOPICS'
export const INIT_REPORTED_USERS = 'INIT_REPORTED_USERS'
export const INIT_REPORTED_COMMENTS = 'INIT_REPORTED_COMMENTS'

